require "user.lazy"
require "user.lsp"
require "user.cmp"
require "user.keymaps"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comments"
require "user.nvim-tree"
require "user.alpha"
require "user.project"
require "user.rust-tools"
require "user.bufferLine"
require "user.impatient"
require "user.lualine"
require "user.toggleterm"
require "user.gitsigns"
require "user.autocommands"
require "user.options"
--[[ vim.cmd("colorscheme terafox") ]]
--[[ vim.cmd("colorscheme terafox") ]]
